# COURSE: A deep understanding of deep learning
## SECTION: Introduction to Python: functions
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202212

# .
# .
# .

# VIDEO: Inputs and outputs

In [1]:
sum([10,20,30])

60

In [2]:
alist = [2,3,4]

sum(alist)

9

In [3]:
# alist(0)
sum(alist)

9

In [4]:
len(alist)

3

In [5]:
# give outputs
listsum = sum(alist)
print('The sum is ' + str(listsum))

The sum is 9

### Exercise

In [6]:
# compute the average
sum(alist) / len(alist)

3.0

# .
# .
# .

# VIDEO: Python modules (numpy, pandas)

In [30]:
import numpy as np

numbers = [1,2,3,4,5]
np.mean(numbers)
np.average(numbers)

np.float64(3.0)

In [31]:
import numpy as np

np.mean(numbers)

np.float64(3.0)

In [32]:
import numpy as np

np.linspace(1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [33]:
# clear the workspace

In [34]:
# new type: numpy array
numbernp = np.array([1,2,3,4,5])

print(numbernp)
print(numbers)

[1 2 3 4 5]
[1, 2, 3, 4, 5]

In [ ]:
print(type(numbernp))
print(type(numbers))

In [36]:
numbernp.min()

np.int64(1)

In [37]:
n = [4,3,5,2,6,1,7]
print(n)
n.sort()
print(n)

[4, 3, 5, 2, 6, 1, 7]
[1, 2, 3, 4, 5, 6, 7]

In [38]:
n = [4,3,5,2,6,1,7]
print(n)
np.sort(n)
print(n)
n = np.sort(n) # notice different variable type; could set back
print(n)

[4, 3, 5, 2, 6, 1, 7]
[4, 3, 5, 2, 6, 1, 7]
[1 2 3 4 5 6 7]

In [39]:
import pandas as pd

# create some random data
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100)>0

# variable labels
labels = ['Temp. (C)','Ice cream']

# create as a dictionary
D = {labels[0]:var1, labels[1]:var2}

# import to pandas dataframe
df = pd.DataFrame(data=D)

In [40]:
df.head()

   Temp. (C)  Ice cream
0  23.726811       True
1  21.785365       True
2  14.913256      False
3  22.655505       True
4  16.838686       True

In [41]:
df.count()

Temp. (C)    100
Ice cream    100
dtype: int64

In [42]:
df.mean()

Temp. (C)    19.279775
Ice cream     0.470000
dtype: float64

### Exercise

In [43]:
# create a pandas dataframe with variables:
# integers from 0 to 10, their square, and their log

import numpy as np

nums = np.array(range(11))

D = {'v1':nums , 'v2':nums**2 , 'v3':np.log(nums)}

df = pd.DataFrame(D)
df

/tmp/ipykernel_8097/1199125325.py:8: RuntimeWarning: divide by zero encountered in log
  D = {'v1':nums , 'v2':nums**2 , 'v3':np.log(nums)}

    v1   v2        v3
0    0    0      -inf
1    1    1  0.000000
2    2    4  0.693147
3    3    9  1.098612
4    4   16  1.386294
5    5   25  1.609438
6    6   36  1.791759
7    7   49  1.945910
8    8   64  2.079442
9    9   81  2.197225
10  10  100  2.302585

# VIDEO: Getting help on functions

In [ ]:
alist = [1,2,3]

sum(alist,10)

In [ ]:
sum??

In [ ]:
help(sum)

In [ ]:
# advanced method

import inspect
import numpy as np
inspect.getsourcelines(np.linspace)

In [ ]:
sum('test')

# .
# .
# .

# VIDEO: Creating functions

In [ ]:
def awesomeFunction():
  print(1+1)

In [ ]:
awesomeFunction
awesomeFunction()

In [ ]:
def SuperAwesomeFunction(input1,input2):
  return input1 + input2

In [12]:
SuperAwesomeFunction(5,8)

NameError: name 'SuperAwesomeFunction' is not defined

In [ ]:
answer = SuperAwesomeFunction(5,8)

In [ ]:
print(answer)

In [ ]:
# with multiple outputs
def awesomeFunction(in1,in2):
  sumres = in1+in2
  prodres = in1*in2
  print('Their sum is ' + str(sumres))
  print('Their product is ' + str(prodres))
  return sumres,prodres

In [ ]:
out1,out2 = awesomeFunction(4,5)

print(out1,out2)

In [ ]:
# lambda functions

littlefun = lambda x : x**2 - 1

littlefun(4)

### Exercise

In [13]:
# create a function that computes a factorial,
# then compare against the numpy factorial function
# hint: import math

def myfactorial(val):
  return np.prod(np.arange(1,val+1))

In [14]:
import math

x = 20 # inaccurate for >~21
print(np.arange(1,x+1))

print(myfactorial(x),math.factorial(x))
math.factorial??

NameError: name 'np' is not defined

# .
# .
# .

# VIDEO: Global and local variable scopes

In [ ]:
# clear the workspace

In [ ]:
def funfun():
  x = 7
  y = 10
  print(x)

In [ ]:
funfun()

In [15]:
x

20

In [16]:
x = 3
print( funfun() )
print( x )
print( y )

NameError: name 'funfun' is not defined

In [ ]:
def funfun():
  print(z)

In [ ]:
funfun()

In [ ]:
z = 3
funfun()

In [ ]:
# rules:
#  1) variables created inside a function are local (accessible only inside the function)
#  2) variables created outside a function are global (accessible in or out of the function)

### Exercise

In [17]:
# write a function that flips a coin N times and reports the average

import numpy as np

def coinflip(N):
  propCoinFlips = np.mean( np.random.randn(N)>0 )
  print( str(N) + ' coin flips had ' + str(propCoinFlips*100) + '% heads.' )

In [18]:
coinflip(2000)

2000 coin flips had 50.349999999999994% heads.

# .
# .
# .

In [19]:
# tangent on copy

a = [4,3]
b = a#[:]
b[0] = 5

print(a)
print(b)

[5, 3]
[5, 3]

In [20]:
print(id(a))
print(id(b))

139312119358144
139312119358144

In [21]:
import copy

a = {'q':1, 'w':2}
b = copy.deepcopy(a)

print(id(a))
print(id(b))

139312109340416
139312109347456

# VIDEO: Classes and object-oriented programming

In [22]:
# class is like a blueprint for a set of attributes and methods
# instance is an example
# class is a cookie cutter, instance is an individual cookie

class model(object):

  # constructor method
  def __init__(self,numlayers,numunits,name):
    self.layers  = numlayers
    self.units   = numunits # these are attributes
    self.name    = name
    self.weights = 10

  # other methods
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} units in the model.')

  def trainTheModel(self,x):
    self.weights += x
    return self.weights

  def __str__(self):
    return f'This is a {self.name} architecture.'

In [23]:
# create an instance and check it
ex = model(2,3,'cnn')
# ex.howManyUnits()
str(ex)

'This is a cnn architecture.'

In [24]:
ex.trainTheModel(3)

13

In [25]:
# Exercise:
# create a new class so that
# 1) the weights is a layers-by-units matrix,
# 2) the weights are changed by multiplying by input x and summing input y

In [26]:
import numpy as np
class model2(object):

  # constructor method
  def __init__(self,numlayers,numunits,name):
    self.layers  = numlayers
    self.units   = numunits # these are attributes
    self.name    = name
    self.weights = np.random.randn(numlayers,self.units)

  # other methods
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f'There are {totalUnits} units in the model.')

  def trainTheModel(self,x,y):
    self.weights = self.weights*x + y

  def __str__(self):
    return f'This is a {self.name} architecture.'

In [27]:
ex1 = model2(2,3,'cnn')
print(ex1.weights)

[[ 1.51355348  0.55192449 -0.37327851]
 [ 0.06541163  0.78774133  0.14909692]]

In [28]:
ex1.trainTheModel(2,3)

In [29]:
ex1.weights

array([[6.02710696, 4.10384898, 2.25344297],
       [3.13082327, 4.57548266, 3.29819384]])